# Generated by Django 5.2.9 on 2026-01-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='chat_files/'),
        ),
    ]
