# Generated by Django 5.2.9 on 2026-01-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_message_file_name_message_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='connections',
            field=models.IntegerField(default=0),
        ),
    ]
