# Generated by Django 5.2.9 on 2026-02-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_message_is_delivered_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
    ]
