# Generated by Django 5.2.9 on 2026-03-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_message_deleted_for_everyone_message_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
