# Generated by Django 6.0 on 2025-12-15 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la permission')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('forename', models.CharField(max_length=100, verbose_name='Prénom')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('Profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('role', models.CharField(choices=[('apprenant', 'Apprenant'), ('entendant', 'Entendant'), ('malentendant', 'Malentendant'), ('employeur', 'Employeur'), ('traducteur', 'Traducteur LSF'), ('admin', 'Administrateur')], default='apprenant', max_length=20, verbose_name='Rôle')),
                ('niveau_perte_auditive', models.CharField(blank=True, max_length=50, null=True, verbose_name='Niveau de perte auditive')),
                ('status_utilisez_vous_un_appareil_auditif', models.BooleanField(default=False, verbose_name='Utilise un appareil auditif')),
                ('level_en_LSF', models.CharField(blank=True, max_length=50, null=True, verbose_name='Niveau en LSF')),
                ('preference_apprentissage', models.JSONField(blank=True, default=list, verbose_name="Préférences d'apprentissage")),
                ('certification', models.CharField(blank=True, max_length=200, null=True, verbose_name='Certification LSF')),
                ('Annee_experience', models.IntegerField(default=0, verbose_name="Années d'expérience")),
                ('niveau_expertise', models.CharField(blank=True, max_length=50, null=True, verbose_name="Niveau d'expertise")),
                ('Competence', models.TextField(blank=True, null=True, verbose_name='Compétences')),
                ('Jour_disponible', models.CharField(blank=True, max_length=200, null=True, verbose_name='Jours disponibles')),
                ('Creneau_horaire_disponible', models.CharField(blank=True, max_length=200, null=True, verbose_name='Créneaux horaires disponibles')),
                ('Tarif_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarif horaire')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'entreprise")),
                ('Domaine_activity', models.CharField(blank=True, max_length=200, null=True, verbose_name="Domaine d'activité")),
                ('Type_company', models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'entreprise")),
                ('Adresse_company', models.TextField(blank=True, null=True, verbose_name="Adresse de l'entreprise")),
                ('Taille_Company', models.CharField(blank=True, max_length=50, null=True, verbose_name="Taille de l'entreprise")),
                ('Site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('langue_parlee', models.JSONField(blank=True, default=list, verbose_name='Langues parlées')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super utilisateur')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('secondary_roles', models.JSONField(blank=True, default=list, verbose_name='Rôles secondaires')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Onboarding terminé')),
                ('onboarding_step', models.IntegerField(default=1, verbose_name='Étape onboarding')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Préférences utilisateur')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('permissions', models.ManyToManyField(blank=True, to='authentication.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
            },
        ),
    ]
