# Generated by Django 5.2.9 on 2025-12-23 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='Adresse_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Annee_experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Competence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Creneau_horaire_disponible',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Domaine_activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Jour_disponible',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Site_web',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Taille_Company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Tarif_horaire',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Type_company',
        ),
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='authentication.permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='certification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='forename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='langue_parlee',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_en_LSF',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='niveau_expertise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='niveau_perte_auditive',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference_apprentissage',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('apprenant', 'Apprenant'), ('entendant', 'Entendant'), ('malentendant', 'Malentendant'), ('employeur', 'Employeur'), ('traducteur', 'Traducteur LSF'), ('admin', 'Administrateur')], default='apprenant', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_utilisez_vous_un_appareil_auditif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='adresse_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='annee_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='competence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='creneau_horaire_disponible',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='domaine_activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jour_disponible',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='taille_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tarif_horaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='type_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
