# Generated by Django 5.2.9 on 2025-12-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_permission_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rôle', 'verbose_name_plural': 'Rôles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='adresse_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='annee_experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='creneau_horaire_disponible',
        ),
        migrations.RemoveField(
            model_name='user',
            name='domaine_activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='jour_disponible',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='site_web',
        ),
        migrations.RemoveField(
            model_name='user',
            name='taille_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tarif_horaire',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type_company',
        ),
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom de la permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du rôle'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='authentication.permission', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='certification',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Certification LSF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='forename',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Super utilisateur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='langue_parlee',
            field=models.JSONField(blank=True, default=list, verbose_name='Langues parlées'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_en_LSF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Niveau en LSF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='niveau_expertise',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Niveau d'expertise"),
        ),
        migrations.AlterField(
            model_name='user',
            name='niveau_perte_auditive',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Niveau de perte auditive'),
        ),
        migrations.AlterField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding terminé'),
        ),
        migrations.AlterField(
            model_name='user',
            name='onboarding_step',
            field=models.IntegerField(default=1, verbose_name='Étape onboarding'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference_apprentissage',
            field=models.JSONField(blank=True, default=list, verbose_name="Préférences d'apprentissage"),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='Préférences utilisateur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('apprenant', 'Apprenant'), ('entendant', 'Entendant'), ('malentendant', 'Malentendant'), ('employeur', 'Employeur'), ('traducteur', 'Traducteur LSF'), ('admin', 'Administrateur')], default='apprenant', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='Rôles secondaires'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_utilisez_vous_un_appareil_auditif',
            field=models.BooleanField(default=False, verbose_name='Utilise un appareil auditif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='user',
            name='Adresse_company',
            field=models.TextField(blank=True, null=True, verbose_name="Adresse de l'entreprise"),
        ),
        migrations.AddField(
            model_name='user',
            name='Annee_experience',
            field=models.IntegerField(default=0, verbose_name="Années d'expérience"),
        ),
        migrations.AddField(
            model_name='user',
            name='Competence',
            field=models.TextField(blank=True, null=True, verbose_name='Compétences'),
        ),
        migrations.AddField(
            model_name='user',
            name='Creneau_horaire_disponible',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Créneaux horaires disponibles'),
        ),
        migrations.AddField(
            model_name='user',
            name='Domaine_activity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Domaine d'activité"),
        ),
        migrations.AddField(
            model_name='user',
            name='Jour_disponible',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Jours disponibles'),
        ),
        migrations.AddField(
            model_name='user',
            name='Profession',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='user',
            name='Site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='user',
            name='Taille_Company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Taille de l'entreprise"),
        ),
        migrations.AddField(
            model_name='user',
            name='Tarif_horaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarif horaire'),
        ),
        migrations.AddField(
            model_name='user',
            name='Type_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'entreprise"),
        ),
    ]
